#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

base_dir="$(dirname -- "$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)")"

if [[ -f "${base_dir}/config/common.env" ]]; then
  source "${base_dir}/config/common.env"
fi

if [[ -f "${base_dir}/config/profile.env" ]]; then
  source "${base_dir}/config/profile.env"
fi

export KAFKA_JMX_OPTS="-Dcom.sun.management.config.file=$base_dir/config/jmx/kafka-jmx.properties"
export LOG_DIR="/pub/opt/Apache/kafka/logs"
EXTRA_ARGS=${EXTRA_ARGS-"${DEFAULT_KAFKA_SERVER_START_ARGS[@]}"}

if [ $# -lt 1 ];
then
	echo "USAGE: $0 [-daemon] server.properties [--override property=value]*"
	exit 1
fi

if [ "x$KAFKA_LOG4J_OPTS" = "x" ]; then
    export KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:$base_dir/config/log4j.properties"
fi

export KAFKA_HEAP_OPTS=${KAFKA_HEAP_OPTS:-'-Xmx5G -Xms256m'}

# Add required options for jktls
export KAFKA_OPTS=${KAFKA_OPTS-""}"\
  --add-opens java.base/sun.nio.ch=ALL-UNNAMED \
  --add-opens java.base/java.io=ALL-UNNAMED \
  --add-opens java.base/sun.security.ssl=ALL-UNNAMED \
  "
#  -javaagent:/usr/share/java/prometheus-jmx-exporter/collector.jar=7071:/pub/opt/Apache/kafka/config/jmx/kafka-jmx.properties \
#  -javaagent:/usr/share/java/prometheus-jmx-exporter/collector.jar=7071:/pub/opt/Apache/kafka/config/jmx/jmx-exporter.yaml \

COMMAND=$1
case ${COMMAND} in
  -daemon)
     EXTRA_ARGS=("-daemon" "${EXTRA_ARGS[@]}")
     shift
    ;;
  *)
    ;;
esac

#echo $EXTRA_ARGS
#EXTRA_ARGS="${EXTRA_ARGS}-javaagent:/usr/share/java/prometheus-jmx-exporter/collector.jar=7071:/pub/opt/Apache/kafka/config/jmx/jmx-exporter.yaml"
#echo $EXTRA_ARGS

#export KAFKA_OPTS="-javaagent:/usr/share/java/prometheus-jmx-exporter/collector.jar=7071:/pub/opt/Apache/kafka/config/jmx/jmx-exporter.yaml"

exec ${base_dir}/bin/kafka-run-class-jmx ${EXTRA_ARGS[@]} ru.sbrf.kafka.distributed.log.DistributedLog "$@"
