tmp_dir: /tmp/installer # путь к временной директории на конечных серверах
wait_for_start: 120 # время в секундах на корректный старт приложения (падает с ошибкой при превышении)
customJavaPath: false # абсолютный путь к используемой java (false для использования java из PATH)
security: SSL__ZK_mTLS_WITH_AUTH__KAFKA_SSL_WITH_AUTH__AUDIT # протокол безопасности
kafka_user: kafka # имя пользователя, от имени которого запускается Kafka
kafka_group: kafka # имя группы от имени которой запускается kafka
zookeeper_user: kafka # имя пользователя, от имени которого запускается ZooKeeper
zookeeper_group: kafka # имя группы от имени которой запускается ZooKeeper
enabled_service: true # создание сервиса и настройка сервиса ../helper/create_service.yml

config_audit:  # настройки аудита
  log: "true"  # запись событий аудита в лог
  rest: "false" # запись событий аудита в rest endpoint
  url: "http://localhost:8084" # префикс url для отправки событий аудита
  metamodel: "v1/metamodel" # суффикс для метамодели
  event: "v1/event" # суффикс для событий
  system_id: "CORAX" # Имя приложения для аудита (по умолчанию "APPLICATION NAME FOR AUDIT")
  trustStorePath: "/pub/opt/Apache/kafka/ssl/kafka.truststore.jks" # путь от inventories/_стенд_/ до файла с trustStore
  trustStorePassword: "{% if keystore_password is defined %}{{ keystore_password }}{%endif%}" # пароль от trustStore
  keyStorePath: "/pub/opt/Apache/kafka/ssl/kafka.keystore.jks" # путь от inventories/_стенд_/ до файла с keyStore
  keyStorePassword: "{% if keystore_password is defined %}{{ keystore_password }}{%endif%}" # пароль от keyStore
  keyPassword: "{% if keystore_password is defined %}{{ keystore_password }}{%endif%}" # пароль от ключа в хранилище
  sslEndpointIdentificationAlgorithm: "all" # использования алгоритмов идентификации SSL сертификатов
  log4j:
    auditFileAppender: "org.apache.log4j.RollingFileAppender"  # класс логирования для аудита
    file: "${kafka.logs.dir}/kafka-audit.log" # путь до файла для записи логов
    layout: "org.apache.log4j.PatternLayout" # класс логов для аудита
    conversionPattern: "[%d] %p %m (%c)%n" # формат логов для аудита
    maxBackupIndex: "10" # максимальное количество файлов для аудита
    maxFileSize: "10MB" # максимальный размер файла для аудита
    logAuditProvider: "DEBUG, auditFileAppender" # уровень логирования для аудита

kafka:
    distr: distrib.zip # имя zip архива с дистрибутивом, размещенного в ./ansible/files/
    installdir: /pub/opt/Apache/kafka # абсолютный путь на конечном сервере к приложению
    logdir: /pub/opt/Apache/kafka/logs # абсолютный путь на конечном сервере к логам приложения
    datadir: /pub/KAFKADATA # абсолютный путь на конечном сервере к данным приложения
    cleanLog: true # очистить путь к логам при установке
    cleanData: false # очистить путь к данным при установке (true если данные не нужны)
    trustStorePath: "ssl/kafka.truststore.jks" # путь от inventories/_стенд_/ до файла с trustStore (или абсолютный на сервере при needUploadJks: false)
    trustStorePassword: "{% if keystore_password is defined %}{{ keystore_password }}{%endif%}" # пароль от trustStore
    keyStorePath: "ssl/kafka.keystore.jks" # путь от inventories/_стенд_/ до файла с keyStore (или абсолютный на сервере при needUploadJks: false)
    keyStorePassword: "{% if keystore_password is defined %}{{ keystore_password }}{%endif%}" # пароль от keyStore
    keyPassword: "{% if keystore_password is defined %}{{ keystore_password }}{%endif%}" # пароль от ключа в хранилище
    audit: #      ^a ^b ^`            ^c     ^b  
      log: "true" #          ^a ^l  ^a     ^k ^b        ^c     ^b            
      rest: "false" #          ^a ^l  ^a     ^k ^b        ^c     ^b      rest endpoint
      trustStorePath: "/pub/opt/Apache/kafka/ssl/kafka.truststore.jks" #    ^c ^b ^l    ^b inventories/_ ^a ^b      _/       ^d          ^a trustStore
      trustStorePassword: "{% if keystore_password is defined %}{{ keystore_password }}{%endif%}" #      ^`     ^l    ^b trustStore
      keyStorePath: "/pub/opt/Apache/kafka/ssl/kafka.keystore.jks" #    ^c ^b ^l    ^b inventories/_ ^a ^b      _/       ^d          ^a keyStore
      keyStorePassword: "{% if keystore_password is defined %}{{ keystore_password }}{%endif%}" #      ^`     ^l    ^b keyStore
      keyPassword: "{% if keystore_password is defined %}{{ keystore_password }}{%endif%}" #      ^`     ^l    ^b      ^n ^g       ^e ^`           ^i  
      url: "http://localhost:8084" #    ^`   ^d     ^a url      ^o    ^b   ^`          ^a     ^k ^b        ^c     ^b  
      metamodel: "v1/metamodel" #  ^a ^c ^d ^d     ^a      ^o      ^b              
      event: "v1/event" #  ^a ^c ^d ^d     ^a      ^o  ^a     ^k ^b    
      system_id: "Synapse.ES Kafka Audit" #

zookeeper:
    distr: distrib.zip # Имя zip архива с дистрибутивом, размещенного в ./ansible/files/
    installdir: /pub/opt/Apache/kafka # абсолютный путь на конечном сервере к приложению
    logdir: /pub/opt/Apache/kafka/logs # абсолютный путь на конечном сервере к логам приложения
    datadir: /pub/zookeeper # абсолютный путь на конечном сервере к данным приложения
    cleanLog: true # очистить путь к логам при установке
    cleanData: false # очистить путь к данным при установке (true если данные не нужны)
    trustStorePath: "ssl/kafka.truststore.jks" # путь от inventories/_стенд_/ до файла с trustStore (или абсолютный на сервере при needUploadJks: false)
    trustStorePassword: "{{ keystore_password }}" # пароль от trustStore
    keyStorePath: "ssl/kafka.keystore.jks" # путь от inventories/_стенд_/ до файла с keyStore (или абсолютный на сервере при needUploadJks: false)
    keyStorePassword: "{{ keystore_password }}" # пароль от keyStore

crxsr:
  distr: distrib.zip # имя zip архива с дистрибутивом, размещенного в ./ansible/files/
  installdir: /pub/opt/Apache/crxsr # абсолютный путь на конечном сервере к приложению
  cleanLog: false # очистить путь к логам при установке
  prop_var:
   "server_port": 8081 # порт на котором работает CRXSR
  sr_user:     # пользователи в schema-registry
    admin:
      psw: "admin"
      role: 'ROLE_ADMIN'
    user:
      psw: "user"
      role: 'ROLE_USER'

crxui:
  server.port: 9090 # порт на котором работает CRXUI
  installdir: /pub/opt/Apache/crxui
  ui_user:                  # словарь с пользователями, паролями и ролями в schema-registry
    admin:                   # имя пользователя
      psw: "admin"   # пароль пользователя
      role: 'ROLE_ADMIN'       # роль пользователя
    user:
      psw: "user"
      role: 'ROLE_USER'
    viewer:
      psw: "viewer"
      role: 'ROLE_VIEWER'
    developer:
      psw: "developer"
      role: 'ROLE_DEVELOPER'
